import { describe, expect, it } from 'vitest';
import { bindCurrentDomain } from '@/lib/bind-domain';
import { domainProofForHost } from '@/lib/domain-proof';
import { DeterministicDomainVerificationService, normalizeRequestHost } from '@/lib/domain-verification';
import { MemoryRepository, publicAgent } from '@/lib/repository';
import { mapDomainBindingRpcResult, mapDomainCompletionRpcResult } from '@/lib/supabase-repository';
import type { Manifest } from '@/lib/types';

const manifest: Manifest = { canonicalName: 'Atlas', role: 'Research Agent', purpose: 'Conduct structured research and preserve validated methods across tasks.', field: 'Research', capabilities: ['Research'], operatingPrinciples: ['Traceability'], memorySchema: ['Sources'], transferableStateRules: ['Preserve history'], privateOwnerDataRules: ['Keep credentials private'], publicIdentitySummary: 'Atlas is a public research identity with traceable methods.' };

async function created(repo = new MemoryRepository(), ownerId = 'owner-a') { return { repo, detail: await repo.create(ownerId, { ...manifest }) }; }

describe('domain binding', () => {
  it('normalizes valid hostnames', () => expect(normalizeRequestHost('App.Example.COM')).toBe('app.example.com'));
  it.each(['https://example.com','example.com/path','example.com:443','user@example.com','localhost','127.0.0.1','[::1]','bad host','example',''])('rejects unsafe host %s', (host: string) => expect(() => normalizeRequestHost(host)).toThrow());
  it('allows the owner to create a pending challenge without changing state', async () => { const { repo, detail } = await created(); const binding = await repo.createPendingDomainBinding(detail.agent.id, 'owner-a', 'app.example.com', 'token'); expect(binding.verificationStatus).toBe('PENDING'); expect((await repo.detail(detail.agent.id))?.agent.currentVersion).toBe(1); });
  it('rejects another owner creating or completing a challenge', async () => { const { repo, detail } = await created(); await expect(repo.createPendingDomainBinding(detail.agent.id, 'owner-b', 'app.example.com', 'token')).rejects.toThrow('authorized'); const binding = await repo.createPendingDomainBinding(detail.agent.id, 'owner-a', 'app.example.com', 'token'); await expect(repo.completeDomainBinding(detail.agent.id, 'owner-b', binding.id)).rejects.toThrow('authorized'); });
  it('leaves Version 1 and canonicalDomain null after failed proof', async () => { const { repo, detail } = await created(); await expect(bindCurrentDomain(detail.agent.id, 'owner-a', 'app.example.com', { repository: repo, verifier: new DeterministicDomainVerificationService(false) })).rejects.toThrow(); const after = await repo.detail(detail.agent.id); expect(after?.agent.currentVersion).toBe(1); expect(after?.agent.canonicalDomain).toBeNull(); });
  it('creates one verified binding, Version 2 and BIND_DOMAIN while preserving the manifest', async () => { const { repo, detail } = await created(); await bindCurrentDomain(detail.agent.id, 'owner-a', 'app.example.com', { repository: repo, verifier: new DeterministicDomainVerificationService() }); const after = await repo.detail(detail.agent.id); expect(after?.agent.currentVersion).toBe(2); expect(after?.agent.canonicalDomain).toBe('app.example.com'); expect(after?.version.versionType).toBe('DOMAIN_BINDING'); expect(after?.version.stateJson.capabilities).toEqual(manifest.capabilities); expect(after?.events.filter((event) => event.eventType === 'BIND_DOMAIN')).toHaveLength(1); expect((await repo.pendingBinding(detail.agent.id))).toBeUndefined(); });
  it('safely rejects duplicate verification', async () => { const { repo, detail } = await created(); await bindCurrentDomain(detail.agent.id, 'owner-a', 'app.example.com', { repository: repo, verifier: new DeterministicDomainVerificationService() }); await expect(bindCurrentDomain(detail.agent.id, 'owner-a', 'app.example.com', { repository: repo, verifier: new DeterministicDomainVerificationService() })).rejects.toThrow('already'); });
  it('prevents a verified domain from attaching to a second agent', async () => { const repo = new MemoryRepository(); const first = await repo.create('owner-a', manifest); const second = await repo.create('owner-a', { ...manifest, canonicalName: 'Beacon' }); await bindCurrentDomain(first.agent.id, 'owner-a', 'app.example.com', { repository: repo, verifier: new DeterministicDomainVerificationService() }); await expect(bindCurrentDomain(second.agent.id, 'owner-a', 'app.example.com', { repository: repo, verifier: new DeterministicDomainVerificationService() })).rejects.toThrow('already bound'); });
  it('public projection exposes verified domain but no owner or token', async () => { const { repo, detail } = await created(); await bindCurrentDomain(detail.agent.id, 'owner-a', 'app.example.com', { repository: repo, verifier: new DeterministicDomainVerificationService() }); const safe = publicAgent((await repo.detail(detail.agent.id))!); expect(safe.canonicalDomain).toBe('app.example.com'); expect(safe).not.toHaveProperty('ownerId'); expect(JSON.stringify(safe)).not.toContain('verificationToken'); });
  it('maps Supabase binding and completion results to the shared contract', async () => { const { repo, detail } = await created(); const pending = mapDomainBindingRpcResult({ id: 'binding', agent_id: detail.agent.id, domain: 'app.example.com', verification_token: 'token', verification_status: 'PENDING', verified_at: null, created_at: '' }); expect(pending.domain).toBe('app.example.com'); await bindCurrentDomain(detail.agent.id, 'owner-a', 'app.example.com', { repository: repo, verifier: new DeterministicDomainVerificationService() }); const completed = await repo.detail(detail.agent.id); expect(mapDomainCompletionRpcResult({ agent: { id: completed!.agent.id, canonical_name: completed!.agent.canonicalName, role: completed!.agent.role, purpose: completed!.agent.purpose, field: completed!.agent.field, owner_id: 'owner-a', status: 'ACTIVE', canonical_domain: 'app.example.com', current_version: 2, created_at: '', updated_at: '' }, owner: { id: 'owner-a', display_name: 'Owner A', slug: 'owner-a', created_at: '' }, version: { id: 'v2', agent_id: completed!.agent.id, version_number: 2, version_type: 'DOMAIN_BINDING', state_json: completed!.version.stateJson, change_summary: '', created_by_owner_id: 'owner-a', created_at: '' }, event: { id: 'event', agent_id: completed!.agent.id, event_type: 'BIND_DOMAIN', actor_owner_id: 'owner-a', metadata_json: { version: '2' }, created_at: '' } }).version.versionType).toBe('DOMAIN_BINDING'); });
  it('well-known proof rejects a Host mismatch', async () => { const { repo, detail } = await created(); await repo.createPendingDomainBinding(detail.agent.id, 'owner-a', 'app.example.com', 'token'); expect(await domainProofForHost(repo, detail.agent.id, 'other.example.com')).toBeUndefined(); expect(await domainProofForHost(repo, detail.agent.id, 'app.example.com')).toMatchObject({ verificationToken: 'token' }); });
});
