import Link from 'next/link';
import { BindDomainForm } from './bind-domain-form';
import { Lifecycle } from './lifecycle';
import type { AgentDetail } from '@/lib/types';

export function AgentDetailView({ detail, privateView, currentDomain }: { detail: AgentDetail; privateView: boolean; currentDomain?: string }) {
  const { agent, owner, version, events } = detail;
  return <main className="mx-auto max-w-5xl px-5 py-12"><div className="flex flex-wrap justify-between gap-4"><div><p className="eyebrow">{agent.id} · State version {agent.currentVersion}</p><h1 className="mt-2 text-4xl font-bold">{agent.canonicalName}</h1><p className="mt-2 text-zinc-400">{agent.role}</p></div>{privateView&&<Link className="btn-muted" href={`/public/agents/${agent.id}`}>View public card</Link>}</div><dl className="card mt-8 grid gap-4 sm:grid-cols-3"><div><dt className="text-xs text-zinc-500">Status</dt><dd>Active</dd></div><div><dt className="text-xs text-zinc-500">Owner</dt><dd>{privateView?owner.displayName:'Not disclosed'}</dd></div><div><dt className="text-xs text-zinc-500">Created</dt><dd>{new Date(agent.createdAt).toLocaleDateString()}</dd></div><div className="sm:col-span-3"><dt className="text-xs text-zinc-500">Purpose</dt><dd>{agent.purpose}</dd></div><div className="sm:col-span-3"><dt className="text-xs text-zinc-500">Canonical domain</dt><dd>{agent.canonicalDomain?<><span className="mr-2 text-blue-300">Verified domain</span>{agent.canonicalDomain}</>:'Not bound'}</dd></div></dl>{privateView&&currentDomain&&<BindDomainForm agentId={agent.id} domain={currentDomain}/>}<section className="card mt-5"><h2 className="text-xl font-bold">{privateView?'Structured Agent State':'Public identity'}</h2>{privateView?<pre className="mt-4 overflow-auto whitespace-pre-wrap text-sm text-zinc-300">{JSON.stringify(version.stateJson,null,2)}</pre>:<p className="mt-3 text-zinc-300">{version.stateJson.publicIdentitySummary}</p>}</section>{privateView&&<><section className="card mt-5"><h2 className="text-xl font-bold">State timeline</h2>{events.map((event)=><div key={event.id} className="mt-4 border-l-2 border-red-500 pl-4"><b>v{event.metadataJson.version} · {event.eventType}</b><p className="text-sm text-zinc-400">{event.eventType==='CREATE'?'Initial Agent Manifest created.':`Verified canonical domain ${event.metadataJson.domain}.`} {new Date(event.createdAt).toLocaleString()}</p></div>)}</section><section className="mt-5"><Lifecycle currentVersion={agent.currentVersion}/></section></>}</main>;
}
